### PR TITLE
Bump Local Core to `8.0.0`

### PR DESCRIPTION
**Pull request by kienstra**
* Bump Local Core to `8.0.0`
* Neither this PR, nor the latest released version of this addon (`1.1.2`) is working with Local `8.0.0`. There's no log to the console about an error when it fails to 'Scan for links', 
* It was working with Local `7.2.2`

### Expected

Clicking 'Scan for links' produces this:
Screenshot 2023-09-22 at 4 42 08 PM

### Actual

It doesn't produce anything, nor show an error in the Terminal when you run Local with `nps`:

clicadsf-b

…though there was a log line from clicking the 'Link Checker' tab:

```sh
9/22/2023, 4:51:45 PM [warn] [main] undefined: Unhandled Rejection. -- {"reason":{},"p":{},"eventId":"273a7f07ad6e43f8804f9d6d078e8780"}
```

### CODE REVIEW

**Comment by kienstra** [comment]
Shoot, Phil was working on this. Closing this in favor of Phil's work.
